import Head from "next/head";

// Style
import * as S from "../src/commons/styles/landing";

export default function Home(): JSX.Element {
  const LANDING_MENUS = [
    {
      name: "자유게시판",
      src: "/images/landing/board.jpg",
      desc: "자신의 생각을 공유해보세요.",
    },
    {
      name: "중고마켓",
      src: "/images/landing/e-commerce.jpg",
      desc: "사용하지 않는 물건을 판매하고, 구매할 수 있어요.",
    },
    {
      name: "마이페이지",
      src: "/images/landing/e-commerce.jpg",
      desc: "나의 정보들을 확인해요.",
    },
    {
      name: "랜덤강아지",
      src: "/images/landing/e-commerce.jpg",
      desc: "다양한 강아지 사진을 볼 수 있어요.",
    },
    // {
    //   name: "openApi",
    //   src: "/images/landing/e-commerce.jpg",
    //   desc: "openApi",
    // },
  ];
  const settings = {
    // className: "center",
    // centerPadding: "60px",
    centerMode: true,
    infinite: true,
    slidesToShow: 2,
    // autoplay: true,
    // autoplaySpeed: 1000,
    responsive: [
      {
        breakpoint: 1024,
        settings: {
          centerMode: false,
          slidesToShow: 1,
        },
      },
    ],
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Contents>
        <S.CustomSlider {...settings}>
          {LANDING_MENUS.map((el, index) => (
            <S.SliderInner key={index}>
              <S.SliderItem>
                <S.ItemFigcaption>
                  <S.Title>{el.name}</S.Title>
                  <S.Desc>{el.desc}</S.Desc>
                </S.ItemFigcaption>
                <S.PageMainImg src={el.src} />
              </S.SliderItem>
            </S.SliderInner>
          ))}
        </S.CustomSlider>
      </S.Contents>
    </>
  );
}
