import Head from "next/head";

// Style
import * as S from "../src/commons/styles/landing";

export default function Home(): JSX.Element {
  const LANDING_MENUS = [
    {
      name: "자유게시판",
      src: "/images/landing/board.jpg",
      desc: "자유롭게 게시물을 등록하고, 수정하고, 삭제할 수 있습니다",
    },
    {
      name: "중고마켓",
      src: "/images/landing/e-commerce.jpg",
      desc: "중고상품을 등록하고, 거래해보세요",
    },
    {
      name: "마이페이지",
      src: "/images/landing/e-commerce.jpg",
      desc: "나를 소개합니다",
    },
    {
      name: "랜덤강아지",
      src: "/images/landing/e-commerce.jpg",
      desc: "랜덤으로 강아지를 볼 수 있습니다",
    },
    {
      name: "openApi",
      src: "/images/landing/e-commerce.jpg",
      desc: "openApi",
    },
  ];
  const settings = {
    dots: true,
    infinite: true,
    speed: 1000,
    slidesToShow: 1,
    slidesToScroll: 1,
    autoplay: true,
    autoplaySpeed: 4000,
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <S.Wrapper>
        <S.Container>
          <S.CustomSlider {...settings}>
            {LANDING_MENUS.map((el, index) => (
              <S.SliderItemWrap key={index}>
                <S.SliderItem>
                  <S.PageInfo>
                    <S.Title>{el.name}</S.Title>
                    <S.Desc>{el.desc}</S.Desc>
                  </S.PageInfo>
                  <S.PageMainImg src={el.src} />
                </S.SliderItem>
              </S.SliderItemWrap>
            ))}
          </S.CustomSlider>
        </S.Container>
      </S.Wrapper>
    </>
  );
}
